# Generated by Django 2.2.1 on 2019-05-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IE', '0002_auto_20190520_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicators',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='date_updated',
        ),
    ]
